# Site settings
# Site title
title:       The answers you seek aren't here...

# Site description
description: Pardon, this page isn't available yet!

# Site description
build:       0.0.1

# Site background
background:  "assets/bg1.mp4"

# Site logo
logo:        "assets/logo.svg"
logo-type:   "assets/logo-type.svg"

# Build settings
markdown:    kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
   - COPYING.txt

sass:
  style:     compressed
svg:
  optimize:  true
